<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="13813" started-at="2018-04-10T16:10:21Z" finished-at="2018-04-10T16:10:35Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="13813" started-at="2018-04-10T16:10:21Z" finished-at="2018-04-10T16:10:35Z">
      <class name="Javalicious.TestConversion">
        <test-method status="PASS" signature="Before()[pri:0, instance:Javalicious.TestConversion@46d56d67]" name="Before" is-config="true" duration-ms="6401" started-at="2018-04-10T12:10:21Z" finished-at="2018-04-10T12:10:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Before -->
        <test-method status="FAIL" signature="TestCase795()[pri:0, instance:Javalicious.TestConversion@46d56d67]" name="TestCase795" duration-ms="6446" started-at="2018-04-10T12:10:28Z" finished-at="2018-04-10T12:10:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [INSIGHTS] but found [Insights]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [INSIGHTS] but found [Insights]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at Javalicious.TestConversion.TestCase795(TestConversion.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase795 -->
        <test-method status="PASS" signature="After()[pri:0, instance:Javalicious.TestConversion@46d56d67]" name="After" is-config="true" duration-ms="919" started-at="2018-04-10T12:10:34Z" finished-at="2018-04-10T12:10:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- After -->
      </class> <!-- Javalicious.TestConversion -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
